import os, glob

env = Environment(ENV = {'PATH':os.environ['PATH']}, h22libs=os.environ['h22libs'])

env.ParseConfig("root-config --glibs --cflags")
env.Append(CCFLAGS = ['-g', '-std=c++11'])
env.Append(CPPPATH = ['$h22libs/include/'], LIBPATH = ['$h22libs/lib/'],LIBS = ['h22'])
env.Append(CPPPATH = ['$ROOTSYS/include/'], LIBPATH = ['$ROOTSYS/lib/'],LIBS = ['TreePlayer','TMVA','Minuit','XMLIO','MLP'])

sources = glob.glob('*.cxx')

for prog in sources:
    env.Program(prog)
